plugins {
    id 'java'
    id 'application'
}

group = 'com.pipphone'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'com.github.bestgamer123-5:CarLib:main-SNAPSHOT'
}

application {
    mainClass = 'com.pipphone.Main'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
